# title: "Onyero Walter Ofuzim"
logo: "/images/OO.png"
email: "onyero.ofuzim@ucalgary.ca"
description: "Electrical and Software Engineering."
linkedin: "https://ca.linkedin.com/in/onyero-walter-ofuzim-189301107"
# twitter_username: ""
# github_username: "Waltberry"

# Build settings
theme: jekyll-theme-minimal
